# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HashEncrypt.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# Author: Song Zifeng
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Window(object):
    def setupUi(self, Window):
        Window.setObjectName("Window")
        Window.resize(1007, 806)
        icon = QtGui.QIcon.fromTheme("hash")
        Window.setWindowIcon(icon)
        self.In = QtWidgets.QTextEdit(Window)
        self.In.setGeometry(QtCore.QRect(40, 40, 381, 180))
        self.In.setObjectName("In")
        self.Out = QtWidgets.QTextBrowser(Window)
        self.Out.setGeometry(QtCore.QRect(560, 40, 361, 410))
        self.Out.setObjectName("Out")
        self.Key = QtWidgets.QTextEdit(Window)
        self.Key.setGeometry(QtCore.QRect(40, 270, 381, 180))
        self.Key.setObjectName("key")
        self.mode = QtWidgets.QComboBox(Window)
        self.mode.setGeometry(QtCore.QRect(440, 100, 100, 21))
        self.mode.setEditable(True)
        self.mode.setCurrentText("")
        self.mode.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.mode.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.mode.setPlaceholderText("")
        self.mode.setObjectName("mode")
        self.mode.addItem("")
        self.mode.addItem("")
        self.mode.addItem("")
        self.mode.addItem("")
        self.mode.addItem("")
        self.mode.addItem("")
        self.mode.addItem("")
        self.label_msg = QtWidgets.QLabel(Window)
        self.label_msg.setGeometry(QtCore.QRect(190, 10, 72, 15))
        self.label_msg.setObjectName("label_msg")
        self.label_key = QtWidgets.QLabel(Window)
        self.label_key.setGeometry(QtCore.QRect(190, 240, 72, 15))
        self.label_key.setObjectName("label_key")
        self.label_digest = QtWidgets.QLabel(Window)
        self.label_digest.setGeometry(QtCore.QRect(710, 10, 72, 15))
        self.label_digest.setObjectName("label_digest")
        self.label_log = QtWidgets.QLabel(Window)
        self.label_log.setGeometry(QtCore.QRect(40, 490, 72, 15))
        self.label_log.setObjectName("label_log")
        self.label_mode = QtWidgets.QLabel(Window)
        self.label_mode.setGeometry(QtCore.QRect(460, 60, 61, 16))
        self.label_mode.setObjectName("label_mode")
        self.log = QtWidgets.QTextBrowser(Window)
        self.log.setGeometry(QtCore.QRect(40, 520, 751, 231))
        self.log.setObjectName("log")
        self.label_length = QtWidgets.QLabel(Window)
        self.label_length.setGeometry(QtCore.QRect(450, 190, 91, 16))
        self.label_length.setObjectName("label_length")
        self.length = QtWidgets.QTextEdit(Window)
        self.length.setGeometry(QtCore.QRect(440, 220, 104, 31))
        self.length.setObjectName("length")
        self.Encrypt = QtWidgets.QPushButton(Window)
        self.Encrypt.setGeometry(QtCore.QRect(450, 340, 93, 28))
        self.Encrypt.setObjectName("Encrypt")

        self.retranslateUi(Window)
        self.mode.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Window)

    def retranslateUi(self, Window):
        _translate = QtCore.QCoreApplication.translate
        Window.setWindowTitle(_translate("Window", "基于hash算法的分组加密软件"))
        self.mode.setItemText(0, _translate("Window", "SM3"))
        self.mode.setItemText(1, _translate("Window", "MD5"))
        self.mode.setItemText(2, _translate("Window", "SHA-1"))
        self.mode.setItemText(3, _translate("Window", "SHA-2-256"))
        self.mode.setItemText(4, _translate("Window", "SHA-2-512"))
        self.mode.setItemText(5, _translate("Window", "SHA-3-256"))
        self.mode.setItemText(6, _translate("Window", "SHA-3-512"))
        self.label_msg.setText(_translate("Window", "输入消息"))
        self.label_key.setText(_translate("Window", "输入密钥"))
        self.label_digest.setText(_translate("Window", "输出摘要"))
        self.label_log.setText(_translate("Window", "日志"))
        self.label_mode.setText(_translate("Window", "选择模式"))
        self.label_length.setText(_translate("Window", "输入分组长度"))
        self.Encrypt.setText(_translate("Window", "加密"))
